config/routes.rb
Rails.application.routes.draw do
  resources :posts do
    resources :comments
    get '/drafts', to: 'posts#drafts', on: :collection
  end
  devise_for :users

  root to: 'posts#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_one_attached :post_picture
  has_many :comments, dependent: :destroy
  paginates_per 3
  validates :title, presence: true

  scope :ordered, ->(direction = :desc) { order(created_at: direction) }
  scope :drafts, ->(value = true) { where(draft: value) }
  scope :with_authors, -> { includes(:author) }
  scope :search, ->(query) do
    return if query.blank?

    where('title ILIKE ? OR title ILIKE ?', "#{query.squish}%", "% #{query.squish}%")
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable,:rrememberable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable,  :validatable

  has_many :posts, foreign_key: :author_id, inverse_of: :author
  has_many :comments, foreign_key: :author_id, inverse_of: :author

  ROLES = {
    user: 0,
    admin: 1
  }.with_indifferent_access.freeze

  enum role: ROLES
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    end
  end

  private
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: %i[ create destroy ]

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.create(comment_params.merge(:author_id => current_user.id))
    redirect_to post_path(@post)
  end

  def destroy

    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])

    authorize @comment
    @comment.destroy
    redirect_to post_path(@post)
  end

  private
  def comment_params
    params.require(:comment).permit( :body)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: %i[ new create edit update destroy]
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    authorize Post

    @posts = Post.drafts(false).ordered.with_authors.search(params[:query]).page params[:page]
  end

  # GET /posts/drafts
  def drafts
    authorize Post

    @posts = current_user.admin? ? Post.all : current_user.posts
    @posts = @posts.drafts.ordered.with_authors
  end

  # GET /posts/1 or /posts/1.json
  def show
    authorize @post
  end

  # GET /posts/new
  def new
    authorize Post

    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    authorize @post
  end

  # POST /posts or /posts.json
  def create
    authorize Post

    @post = Post.new(post_params)
    # @post.post_picture.attach(params[:post_picture])
    @post.author = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    authorize @post

    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    authorize @post

    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body, :draft, :post_picture)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_comment.html.erb
<p class="fw-bold mb-1">
  <%= comment.author.username %>
  <% if policy(comment).destroy? %>
    <%= link_to '', [comment.post, comment], method: :delete, data: { confirm: 'Are you sure?' }, class: "bi bi-trash-fill text-danger fs-4 ms-2" %>
  <% end %>
</p>
<p class="mb-4">
  <%= comment.body %>
</p>

app/views/comments/_form.html.erb
<%= form_with model: [ @post, @post.comments.build ] do |form| %>
  <p>
    <%= form.text_area :body, class: "form-control w-50" %>
  </p>
  <p>
    <%= form.submit class: "btn btn-primary" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twittogram</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'styles' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</head>

<body>


<div class="container py-3">
  <header class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
      <%= image_tag("/logo.png", class: "logo-img") %>
      <!-- <svg xmlns="http://www.w3.org/2000/svg" width="40" height="32" class="me-2" viewBox="0 0 118 94" role="img"><title>Bootstrap</title><path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z" fill="currentColor"></path></svg> -->
      <span class="fs-4">Twittogram</span>
    </a>

    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
      <%= link_to 'Home', root_path, class: "me-3 py-2 text-dark text-decoration-none" %>
      <% if user_signed_in? %>
        <div class="py-1 dropdown text-end">
          <a href="#" class="d-block link-dark text-decoration-none dropdown-toggle" id="dropdownUser" data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png" alt="mdo" width="32" height="32" class="rounded-circle">
          </a>

          <ul class="dropdown-menu dropdown-menu-end text-small " aria-labelledby="dropdownUser">
            <li>
              <div class="text-center p-3">
                <img src="https://cdn.icon-icons.com/icons2/1378/PNG/512/avatardefault_92824.png" alt="mdo" width="64" height="64" class="rounded-circle mb-2">
                <div class=""><%= current_user.username %>
                <% if current_user.admin? %>
                  (admin)
                <% end %>
                </div>
                <div class="fw-lighter"><%= current_user.email %></div>
              </div>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><%= link_to 'Drafts', drafts_posts_path, class: "dropdown-item" %></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><%= link_to 'Log out', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure' }, class: "dropdown-item" %></li>
          </ul>
        </div>


      <% else %>
        <%= link_to 'Log in', new_user_session_path, class: "py-2 text-dark text-decoration-none" %>
      <% end %>
    </nav>
  </header>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

</div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, class: "form-label" %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :body, class: "form-label" %>
    <%= form.text_area :body, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.label :post_picture, class: "form-label" %>
    <%= form.file_field :post_picture, class: "form-control" %>
  </div>

  <div class="mb-3">
    <%= form.check_box :draft %>
    <%= form.label :draft, class: "form-label d-inline-block ms-2" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/posts/_posts.html.erb
<% posts.each do |post| %>
  <div class="mb-5">
    <p class="mb-1"><%= link_to post.title, post, class:"fs-4 text-dark text-decoration-none" %>
      <% if policy(post).update? %>
        <%= link_to '', edit_post_path(post), class: "bi bi-pencil-fill text-primary fs-4 ms-5" %>
      <% end %>

      <% if policy(post).destroy? %>
        <%= link_to '', post, method: :delete, data: { confirm: 'Are you sure?' }, class: "bi bi-trash-fill text-danger fs-4" %>
      <% end %>
    </p>
    <p class="mb-1"><a class="fst-italic text-dark text-decoration-none" href="#"><%= post.author.username %></a></p>
    <p class="mb-1"><%= link_to post.created_at, post, class:"fst-italic text-dark text-decoration-none" %></p>
    <p>

      <% if post.body.length < 250 %>
        <%= post.body %>
      <% else %>
        <%= post.body[0,250] %> <%= link_to "Read more...", post %>
      <% end %>
    </p>

    <% if post.post_picture.attached? %>
      <img src="<%=(url_for(post.post_picture))%>" class="mw-100" alt="">
    <% end %>
    <div class="mt-3">
      <!--          <span class="me-3"><i class="bi bi-heart-fill fs-6 me-1 text-danger"></i> 0 likes</span>-->
      <span><%= link_to '', post, class:"bi bi-chat-left-text-fill fs-6 me-1 text-dark text-decoration-none" %>
        <%= link_to "#{pluralize(post.comments.length, 'comment')}", post, class:"text-dark text-decoration-none" %>  </span>
    </div>


    <p></p>
  </div>
<% end %>

app/views/posts/drafts.html.erb
<div class="row">
  <div class="col-md-9 col-12">
    <div class="row align-items-center mb-4">
      <div class="col-auto"><h4 class="pt-2">Drafts</h4></div>
    </div>

    <%= render 'posts', posts: @posts %>


  </div>
</div>

app/views/posts/edit.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <h4 class="text-center">Editing Post</h4>
<%= render 'form', post: @post %>

    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', posts_path %>

  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <div class="col-11">
    <div class="row align-items-center mb-4">
      <div class="col-auto mb-2"><h4 class="pt-2">Your feed</h4></div>
      <div class="col-auto">
        <%= link_to 'New Post', new_post_path, class: "btn btn-primary" %>
      </div>

      <div class="col-md-6 col-12 ms-auto">
        <%= form_with method: :get, class: "row row-cols-lg-auto g-3 align-items-center" do |form|  %>
          <div class="col-12">
            <%= form.text_field :query, class:"form-control", placeholder: "Search", value: params[:query] %>
          </div>
          <div class="col-12">
            <%= form.submit "Search", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-9 col-12">


    <%= render 'posts', posts: @posts %>

    <%= paginate @posts %>
  </div>
</div>

app/views/posts/new.html.erb
<div class="row justify-content-center">
  <div class="col-10">
    <h4 class="text-center">New Post</h4>
<%= render 'form', post: @post %>

    <%= link_to 'Back', posts_path %>
  </div>
</div>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>
<p class="fs-3 fw-bold mb-1">
  <%= @post.title %>
</p>
<p class="fst-italic text-dark mb-1">
  post by <%= @post.author.username %>
</p>
<p class="fst-italic text-dark">
  <%= @post.created_at %>
</p>
<p>
  <%= @post.body %>
</p>
<% if @post.post_picture.attached? %>
  <img src="<%=(url_for(@post.post_picture))%>" class="mw-100" alt="">
<% end %>




<p class="fs-4 fw-bold mt-5">Comments</p>
<%= render @post.comments %>

<p class="fs-4 fw-bold mt-5">Add a comment:</p>
<%= render 'comments/form' %>